const express = require('express')
const cors = require('cors')
const Database = require('./Connection/Database')
const Admin = require('./Routing/AdminRoute')
const User = require('./Routing/UserRoute')
const app = express()
app.use(express.json())
app.use(cors())
Database.connect()
app.listen(process.env.PORT || 5000)
app.use('/Bookstore', Admin)
app.use('/Bookstore', User)
console.log("We are listening to http://localhost:5000")
module.exports = app