const express = require('express')
const Admin = require('../Controller/AdminControl')
const AdminAuth = require('../Authentication/AdminAuth')
const router = express.Router()
router.post('/AddAdmin', AdminAuth, Admin.AddAdmin)
router.post('/UpdateAdmin/:id', AdminAuth, Admin.EditAdmin)
router.delete('/DeleteAdmin/:id', AdminAuth, Admin.DeleteAdmin)
router.get('/Login', Admin.Login)
router.get('/Logout', Admin.Logout)
router.post('/AddBook', AdminAuth, Admin.AddBook)
router.put('/UpdateBook/:id', AdminAuth, Admin.UpdateBook)
router.get('/FindBook', AdminAuth, Admin.FindBook)
router.delete('/DeleteBook', AdminAuth, Admin.DeleteBook)
module.exports = router