const User = require("../Controller/UserControl")
const userToken = require("../Authentication/CheckExpiryToken")
const express = require("express")
const router = express.Router()
router.post("/UserSignup", User.SignUp)
router.get("/UserLogin", userToken, User.Login)
router.get("/UserLogout/:id", User.Logout)
router.put("/UserUpdateinfo/:id", User.UpdateInfo)
router.get("/UserForgetPassword", User.ForgetPassword)
router.post("/UserResetPassword", User.ResetPassword)
router.get("/UserDeleteAccRequest/:id", User.DeleteAccRequset)
router.delete("/UserRemoveAccount/:id", User.RemoveAcc)
router.post("/AddToCart", User.AddToCart)
router.get("/BuyBooks", User.BuyBooks)
router.get("/ShowCart", User.ShowCart)
router.get("/RemoveFromCart", User.DeleteFromCart)
router.get("/ShowPayments", User.ShowPayments)

module.exports = router